package com.goodpon.domain.coupon.user.exception

import com.goodpon.domain.BaseException

class UserCouponAlreadyRedeemedException : BaseException("이미 사용된 쿠폰입니다.")